project:
  output-dir: ./_site/ko

website:
  page-navigation: true
  title: "조나단"

  page-footer:
    left: "&copy; Copyright 2023, Jonathan Binder"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  navbar:
    left:
      - href: index.qmd
        text: 홈
      - href: projects/index.qmd
        text: 프로젝트들
      - href: cv/index.qmd
        text: CV
    right: 
      - href: ../ko
        text: 한국어
      - href: ../en
        text: English

lang: ko

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



